spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  h2.console.enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/route}?currentSchema=apigateway
    username: ${DATASOURCE_USER:apigateway_ms}
    password: ${DATASOURCE_PASSWORD:apigateway_ms}
  liquibase:
    enabled: true
    parameters:
      schema: route
      text_array_type: ARRAY
    change-log: classpath:db/changelog-master.xml
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    ROOT: info
    com.flixbus.apigateway: debug
    org:
      springframework: debug
    org.apache.coyote.http11: info

agigateway:
  jwt:
    secret: test