replicaCount: 2
image:
  repository: "pomeo44/ms-apigateway"
  tag: "2"
  pullPolicy: IfNotPresent
container:
  port:
    http: 8080
    debug: 5005
service:
  type: LoadBalancer
  port:
    http: 8080
    debug: 5005
